import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

interface Slip {
  slip_id: number;
  advice: string;
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/favicon-32x32.png" />
      </Head>

      <main>Advice #</main>

      <footer>
        <div className="attribution">
          Challenge by{" "}
          <a
            href="https://www.frontendmentor.io?ref=challenge"
            target="_blank"
            rel="noreferrer"
          >
            Frontend Mentor
          </a>
          . Coded by <a href="#">Your Name Here</a>.
        </div>
      </footer>
    </div>
  );
};

export default Home;
