import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

interface Slip {
  slip_id: number;
  advice: string;
}

const Home: NextPage = () => {
  const [slip, setSlip] = useState<Slip | null>({
    slip_id: 117,
    advice:
      "It is easy to sit up and take notice, what's difficult is getting up and taking action.",
  });
  const { slip_id, advice } = slip as Slip;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/favicon-32x32.png" />
      </Head>

      <main>
        <article className="advice-slip">
          <h4 className="advice-slip__title">ADVICE #{slip_id}</h4>
          <h2 className="advice-slip__content">&quot;{advice}&quot;</h2>
          <img
            className="advice-slip__divider"
            src="/images/pattern-divider-mobile.svg"
            srcSet="/images/pattern-divider-mobile.svg 375w, /images/pattern-divider-mobile.svg 1440w"
          />
          <br />
          <button className="advice-slip__button">
            <img src="/images/icon-dice.svg" />
          </button>
        </article>
      </main>

      <footer>
        <div className="attribution">
          Challenge by{" "}
          <a
            href="https://www.frontendmentor.io?ref=challenge"
            target="_blank"
            rel="noreferrer"
          >
            Frontend Mentor
          </a>
          . Coded by <a href="#">Your Name Here</a>.
        </div>
      </footer>
    </div>
  );
};

export default Home;
